name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Hapus folder dokumen agar tidak ditolak HF
          rm -rf "01_Proposal_&_Analisis"
          rm -rf "02_Design_Documents"
          rm -rf ".github"

          # 2. Reset total riwayat Git
          rm -rf .git
          git init
          git config user.email "felicia2305@example.com"
          git config user.name "Felicia2305"
          
          # 3. PASTIKAN NAMA BRANCH ADALAH main
          git checkout -b main
          
          # 4. Masukkan semua file dan commit
          git add .
          git commit -m "Deploy clean code to Hugging Face"

          # 5. Push paksa ke Hugging Face branch main
          git push --force https://Felicia2305:$HF_TOKEN@huggingface.co/spaces/Felicia2305/ki-service-helper main