name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "felicia2305@example.com"
          git config --global user.name "Felicia2305"
          
          # MENGHAPUS FOLDER DOKUMEN YANG TIDAK DIBUTUHKAN SERVER HF
          # Kita hapus agar tidak ditolak karena file binary (PDF/PNG)
          rm -rf "01_Proposal_&_Analisis"
          rm -rf "02_Design_Documents"
          
          # Commit perubahan sementara ini (hanya di dalam environment GitHub Action)
          git add .
          git commit -m "Clean up docs for Hugging Face deployment" || echo "No changes to commit"
          
          # Push paksa ke Hugging Face
          git push --force https://Felicia2305:$HF_TOKEN@huggingface.co/spaces/Felicia2305/ki-service-helper main